
TEXT_COLOR_NAV = [
    ('#000000', 'Noir'),
    ('#FFFFFF', 'Blanc'),
    ('#FF5733', 'Orange'),
    ('#33FF57', 'Vert'),
    ('#3357FF', 'Bleu'),
    ('#FFD700', 'Jaune'),
    ('#800080', 'Violet'),
    ('#FFC0CB', 'Rose'),
    ('#D3D3D3', 'Gris clair'),

    # Mélanges de couleurs
    ('#3498DB', 'Bleu'),
    ('#FF5733', 'Orange vif'),
    ('#1ABC9C', 'Turquoise'),
    ('#E74C3C', 'Rouge'),
    ('#9B59B6', 'Violet'),
    ('#F39C12', 'Jaune'),

    # Couleurs foncées
    ('#333333', 'Gris foncé'),
    ('#212121', 'Noir charbon'),
    ('#1A1A1A', 'Gris ardoise foncé'),
    ('#2C3E50', 'Bleu marine foncé'),
    ('#34495E', 'Gris bleu foncé'),
    ('#555555', 'Gris moyen foncé'),
    ('#7F8C8D', 'Gris ardoise'),
    ('#6A1B9A', 'Violet foncé'),
    ('#9B59B6', 'Violet prune'),
    ('#8E44AD', 'Violet foncé'),
    ('#E74C3C', 'Rouge foncé'),
    ('#C0392B', 'Rouge bordeaux'),
    ('#D35400', 'Orange brûlé'),
    ('#F39C12', 'Jaune foncé'),
    ('#16A085', 'Vert foncé'),
    ('#27AE60', 'Vert forêt foncé'),
    ('#2980B9', 'Bleu foncé'),
    ('#1ABC9C', 'Turquoise foncé'),

    # Dégradés
    ('linear-gradient(to right, #FF7F50, #FF1493)', 'Dégradé Rose-Orangé'),
    ('linear-gradient(to right, #2980B9, #8E44AD)', 'Dégradé Bleu-Violet'),
    ('linear-gradient(to right, #F39C12, #F1C40F)', 'Dégradé Jaune-Or'),

    # Couleurs complémentaires
    ('#27AE60', 'Vert'),
    ('#2C3E50', 'Bleu marine'),
    ('#FFDAB9', 'Pêche'),
    ('#BDC3C7', 'Gris clair'),
]
TEXT_COLOR_NAV_CUSOR  = [
    ('#000000', 'Noir'),
    ('#FFFFFF', 'Blanc'),
    ('#FF5733', 'Orange'),
    ('#33FF57', 'Vert'),
    ('#3357FF', 'Bleu'),
    ('#FFD700', 'Jaune'),
    ('#800080', 'Violet'),
    ('#FFC0CB', 'Rose'),
    ('#D3D3D3', 'Gris clair'),

    # Mélanges de couleurs
    ('#3498DB', 'Bleu'),
    ('#FF5733', 'Orange vif'),
    ('#1ABC9C', 'Turquoise'),
    ('#E74C3C', 'Rouge'),
    ('#9B59B6', 'Violet'),
    ('#F39C12', 'Jaune'),

    # Couleurs foncées
    ('#333333', 'Gris foncé'),
    ('#212121', 'Noir charbon'),
    ('#1A1A1A', 'Gris ardoise foncé'),
    ('#2C3E50', 'Bleu marine foncé'),
    ('#34495E', 'Gris bleu foncé'),
    ('#555555', 'Gris moyen foncé'),
    ('#7F8C8D', 'Gris ardoise'),
    ('#6A1B9A', 'Violet foncé'),
    ('#9B59B6', 'Violet prune'),
    ('#8E44AD', 'Violet foncé'),
    ('#E74C3C', 'Rouge foncé'),
    ('#C0392B', 'Rouge bordeaux'),
    ('#D35400', 'Orange brûlé'),
    ('#F39C12', 'Jaune foncé'),
    ('#16A085', 'Vert foncé'),
    ('#27AE60', 'Vert forêt foncé'),
    ('#2980B9', 'Bleu foncé'),
    ('#1ABC9C', 'Turquoise foncé'),

    # Dégradés
    ('linear-gradient(to right, #FF7F50, #FF1493)', 'Dégradé Rose-Orangé'),
    ('linear-gradient(to right, #2980B9, #8E44AD)', 'Dégradé Bleu-Violet'),
    ('linear-gradient(to right, #F39C12, #F1C40F)', 'Dégradé Jaune-Or'),

    # Couleurs complémentaires
    ('#27AE60', 'Vert'),
    ('#2C3E50', 'Bleu marine'),
    ('#FFDAB9', 'Pêche'),
    ('#BDC3C7', 'Gris clair'),
]

TYPE_BOUTIQUE_CHOICES = [
        ('petite', 'Petite Boutique'),
        ('croissance', 'Boutique en Croissance'),
        ('grande', 'Grande Boutique'),
    ]
    
SOURCE_DECOUVERTE_CHOICES = [
        ('reseaux_sociaux', 'Réseaux sociaux (Facebook, Instagram, Twitter, etc.)'),
        ('bouche_a_oreille', 'Bouche-à-oreille'),
        ('publicite', 'Publicité (en ligne, TV, etc.)'),
        ('recherche_google', 'Recherche Google'),
        ('blog_articles', 'Articles de blog ou forums'),
        ('email_marketing', 'Email marketing'),
        ('partenariats', 'Partenariats ou affiliations'),
        ('publications_mediatiques', 'Publications médiatiques (journaux, magazines, TV)'),
        ('autre', 'Autre'),
    ]
    
PRODUITS_VENDUS_CHOICES = [
    ('Vêtements et accessoires', 'vetements'),
    ('Vêtements pour hommes', 'hommes'),
    ('Vêtements pour femmes', 'femmes'),
    ('Vêtements pour enfants', 'enfants'),
    ('Accessoires de mode', 'accessoires'),
    ('Alimentation et boissons', 'alimentaire'),
    ('Produits alimentaires de base', 'produits_basiques'),
    ('Fruits et légumes', 'fruits_legumes'),
    ('Boissons', 'boissons'),
    ('Produits laitiers', 'produits_laitiers'),
    ('Café et thé', 'cafe_the'),
    ('Électronique et appareils ménagers', 'electronique'),
    ('Téléphones mobiles et accessoires', 'smartphones'),
    ('Appareils électroménagers', 'appareils_electromenagers'),
    ('Ordinateurs et accessoires', 'ordinateurs'),
    ('Cosmétiques et soins personnels', 'cosmetiques'),
    ('Produits de beauté', 'beaute'),
    ('Produits d’hygiène', 'hygiene'),
    ('Parfums', 'parfums'),
    ('Matériel de construction et d\'ameublement', 'construction'),
    ('Matériaux de construction', 'materiaux'),
    ('Meubles', 'meubles'),
    ('Décoration intérieure', 'decoration'),
    ('Produits de santé et médicaments', 'sante'),
    ('Médicaments en vente libre', 'medicaments'),
    ('Produits de bien-être', 'bien_etre'),
    ('Artisanat et objets traditionnels', 'artisanat'),
    ('Sculptures', 'sculptures'),
    ('Peintures', 'peintures'),
    ('Objets traditionnels', 'objets_traditionnels'),
    ('Automobiles et pièces détachées', 'automobile'),
    ('Véhicules neufs et d\'occasion', 'vehicules'),
    ('Pièces détachées', 'pieces_detachees'),
    ('Produits agricoles', 'agricole'),
    ('Grains et céréales', 'grains'),
    ('Culture vivrière', 'vivrier'),
    ('Cultures industrielles', 'industriels'),
    ('Produits chimiques et agricoles', 'chimie_agricole'),
    ('Fertilisants', 'engrais'),
    ('Pesticides et herbicides', 'pesticides'),
    ('Semences', 'semences'),
]

 # Liste complète de couleurs avec leurs codes hexadécimaux
COULEURS = [
        ('', ''),
        ('#FF5733', 'Rouge Orangée'),
        ('#FF6347', 'Tomate'),
        ('#FF4500', 'Rouge Orange'),
        ('#FF0000', 'Rouge'),
        ('#800000', 'Rouge Foncé'),
        ('#32CD32', 'Vert Lime'),
        ('#228B22', 'Vert Forêt'),
        ('#006400', 'Vert Foncé'),
        ('#008000', 'Vert'),
        ('#00FF00', 'Vert Clair'),
        ('#0000FF', 'Bleu'),
        ('#1E90FF', 'Bleu Dodger'),
        ('#4682B4', 'Bleu Acier'),
        ('#5F9EA0', 'Bleu Grisé'),
        ('#00008B', 'Bleu Marine'),
        ('#000080', 'Navy'),
        ('#8A2BE2', 'Violet'),
        ('#6A5ACD', 'Violet Cadet'),
        ('#7B68EE', 'Violet Clair'),
        ('#800080', 'Violet Foncé'),
        ('#FFD700', 'Or'),
        ('#FFFF00', 'Jaune'),
        ('#F0E68C', 'Jaune Pâle'),
        ('#DAA520', 'Or Marron'),
        ('#FFFACD', 'Jaune Clair'),
        ('#FF1493', 'Rose Chaud'),
        ('#FF69B4', 'Rose'),
        ('#C71585', 'Rose Fuchsia'),
        ('#D3D3D3', 'Gris Clair'),
        ('#A9A9A9', 'Gris'),
        ('#808080', 'Gris Moyen'),
        ('#696969', 'Gris Foncé'),
        ('#000000', 'Noir'),
        ('#FFFFFF', 'Blanc'),
        ('#D3D3D3', 'Gris Clair'),
        ('#F5F5F5', 'Gris Très Clair'),
        ('#C0C0C0', 'Argent'),
        ('#A52A2A', 'Marron'),
        ('#8B4513', 'Marron Foncé'),
        ('#D2691E', 'Chocolat'),
        ('#CD5C5C', 'Rouge Indien'),
        ('#F08080', 'Corail Clair'),
        ('#FA8072', 'Saumon'),
        ('#E9967A', 'Saumon Foncé'),
        ('#F4A460', 'Sable'),
        ('#D2B48C', 'Brun'),
        ('#FFF8DC', 'Blanc Crème'),
        # Ajoutez d'autres couleurs selon vos besoins
    ]
