# Generated by Django 5.1.4 on 2025-02-19 14:15

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200)),
                ('numero_client', models.CharField(max_length=15)),
                ('date_commande', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('html_contenu', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=50)),
                ('lieu_de_livraison', models.CharField(blank=True, max_length=255, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('panier', models.BooleanField(default=False)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('etat', models.CharField(choices=[('Neuf', 'Neuf'), ('Occasion', 'Occasion'), ('Reconditionné', 'Reconditionné')], default='Neuf', max_length=50)),
                ('video_promotionnelle', models.URLField(blank=True, null=True)),
                ('mise_en_avant', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='SupportClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('responsable_support', 'Responsable Support'), ('assistant_support', 'Assistant Support'), ('technicien_support', 'Technicien Support')], max_length=50)),
                ('validation_compte', models.CharField(choices=[('accordé', 'Accordé'), ('non accordé', 'Non accordé')], max_length=20)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(default='identifiant_par_defaut', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom_complet', models.CharField(db_index=True, max_length=200)),
                ('numero', models.CharField(max_length=15)),
                ('nom_boutique', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='client_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='client_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_commande', to='shop.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produits', to='shop.tag'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identifiant_unique', models.CharField(default='warabaguinee224', max_length=100, unique=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=15, unique=True)),
                ('nom_boutique', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('statut_validation_compte', models.CharField(choices=[('attente', 'Attente'), ('valider', 'Valider'), ('invalider', 'Invalider')], default='attente', max_length=10)),
                ('produits_vendus', models.CharField(blank=True, default=None, max_length=225)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='details/')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.produit')),
                ('utilisateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='produit_images', to='shop.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='shop.utilisateur'),
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur_fond', models.CharField(choices=[('#FFFFFF', 'Blanc'), ('#000000', 'Noir'), ('#FF5733', 'Orange'), ('#33FF57', 'Vert'), ('#3357FF', 'Bleu'), ('#FFD700', 'Jaune'), ('#800080', 'Violet'), ('#FFC0CB', 'Rose'), ('#D3D3D3', 'Gris clair'), ('#3498DB', 'Bleu'), ('#FF5733', 'Orange vif'), ('#1ABC9C', 'Turquoise'), ('#E74C3C', 'Rouge'), ('#9B59B6', 'Violet'), ('#F39C12', 'Jaune'), ('#F39C12', 'Jaune'), ('#333333', 'Gris foncé'), ('#212121', 'Noir charbon'), ('#1A1A1A', 'Gris ardoise foncé'), ('#2C3E50', 'Bleu marine foncé'), ('#34495E', 'Gris bleu foncé'), ('#555555', 'Gris moyen foncé'), ('#7F8C8D', 'Gris ardoise'), ('#6A1B9A', 'Violet foncé'), ('#9B59B6', 'Violet prune'), ('#8E44AD', 'Violet foncé'), ('#E74C3C', 'Rouge foncé'), ('#C0392B', 'Rouge bordeaux'), ('#D35400', 'Orange brûlé'), ('#F39C12', 'Jaune foncé'), ('#16A085', 'Vert foncé'), ('#27AE60', 'Vert forêt foncé'), ('#2980B9', 'Bleu foncé'), ('#1ABC9C', 'Turquoise foncé'), ('linear-gradient(to right, #FF7F50, #FF1493)', 'Dégradé Rose-Orangé'), ('linear-gradient(to right, #2980B9, #8E44AD)', 'Dégradé Bleu-Violet'), ('linear-gradient(to right, #F39C12, #F1C40F)', 'Dégradé Jaune-Or'), ('#27AE60', 'Vert'), ('#2C3E50', 'Bleu marine'), ('#FFDAB9', 'Pêche'), ('#BDC3C7', 'Gris clair')], default='#FFFFFF', max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_settings', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=200)),
                ('email_utilisateur', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='LocalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_localisation/')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_localisation', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='InformationsSupplementaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_boutique', models.CharField(choices=[('petite', 'Petite Boutique'), ('croissance', 'Boutique en Croissance'), ('grande', 'Grande Boutique')], max_length=50)),
                ('produits_vendus', models.CharField(choices=[('Vêtements et accessoires', 'vetements'), ('Vêtements pour hommes', 'hommes'), ('Vêtements pour femmes', 'femmes'), ('Vêtements pour enfants', 'enfants'), ('Accessoires de mode', 'accessoires'), ('Alimentation et boissons', 'alimentaire'), ('Produits alimentaires de base', 'produits_basiques'), ('Fruits et légumes', 'fruits_legumes'), ('Boissons', 'boissons'), ('Produits laitiers', 'produits_laitiers'), ('Café et thé', 'cafe_the'), ('Électronique et appareils ménagers', 'electronique'), ('Téléphones mobiles et accessoires', 'smartphones'), ('Appareils électroménagers', 'appareils_electromenagers'), ('Ordinateurs et accessoires', 'ordinateurs'), ('Cosmétiques et soins personnels', 'cosmetiques'), ('Produits de beauté', 'beaute'), ('Produits d’hygiène', 'hygiene'), ('Parfums', 'parfums'), ("Matériel de construction et d'ameublement", 'construction'), ('Matériaux de construction', 'materiaux'), ('Meubles', 'meubles'), ('Décoration intérieure', 'decoration'), ('Produits de santé et médicaments', 'sante'), ('Médicaments en vente libre', 'medicaments'), ('Produits de bien-être', 'bien_etre'), ('Artisanat et objets traditionnels', 'artisanat'), ('Sculptures', 'sculptures'), ('Peintures', 'peintures'), ('Objets traditionnels', 'objets_traditionnels'), ('Automobiles et pièces détachées', 'automobile'), ("Véhicules neufs et d'occasion", 'vehicules'), ('Pièces détachées', 'pieces_detachees'), ('Produits agricoles', 'agricole'), ('Grains et céréales', 'grains'), ('Culture vivrière', 'vivrier'), ('Cultures industrielles', 'industriels'), ('Produits chimiques et agricoles', 'chimie_agricole'), ('Fertilisants', 'engrais'), ('Pesticides et herbicides', 'pesticides'), ('Semences', 'semences')], default='vetements', max_length=241)),
                ('source_decouverte', models.CharField(choices=[('reseaux_sociaux', 'Réseaux sociaux (Facebook, Instagram, Twitter, etc.)'), ('bouche_a_oreille', 'Bouche-à-oreille'), ('publicite', 'Publicité (en ligne, TV, etc.)'), ('recherche_google', 'Recherche Google'), ('blog_articles', 'Articles de blog ou forums'), ('email_marketing', 'Email marketing'), ('partenariats', 'Partenariats ou affiliations'), ('publications_mediatiques', 'Publications médiatiques (journaux, magazines, TV)'), ('autre', 'Autre')], max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(choices=[('GNF', 'GNF'), ('FCFA', 'FCFA'), ('$', 'USD'), ('€', 'EUR'), ('₦', 'NGN'), ('Esc', 'CVE'), ('FCE', 'FCE'), ('L$', 'LCF')], default='GNF', max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devise', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='profil_images/')),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField(blank=True, help_text='Note entre 1 et 5 étoiles', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='shop.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='shop.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='shop.utilisateur'),
        ),
        migrations.CreateModel(
            name='BoutiqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur_texte', models.CharField(choices=[('#000000', 'Noir'), ('#FFFFFF', 'Blanc'), ('#FF5733', 'Orange'), ('#33FF57', 'Vert'), ('#3357FF', 'Bleu'), ('#FFD700', 'Jaune'), ('#800080', 'Violet'), ('#FFC0CB', 'Rose'), ('#D3D3D3', 'Gris clair'), ('#3498DB', 'Bleu'), ('#FF5733', 'Orange vif'), ('#1ABC9C', 'Turquoise'), ('#E74C3C', 'Rouge'), ('#9B59B6', 'Violet'), ('#F39C12', 'Jaune'), ('#333333', 'Gris foncé'), ('#212121', 'Noir charbon'), ('#1A1A1A', 'Gris ardoise foncé'), ('#2C3E50', 'Bleu marine foncé'), ('#34495E', 'Gris bleu foncé'), ('#555555', 'Gris moyen foncé'), ('#7F8C8D', 'Gris ardoise'), ('#6A1B9A', 'Violet foncé'), ('#9B59B6', 'Violet prune'), ('#8E44AD', 'Violet foncé'), ('#E74C3C', 'Rouge foncé'), ('#C0392B', 'Rouge bordeaux'), ('#D35400', 'Orange brûlé'), ('#F39C12', 'Jaune foncé'), ('#16A085', 'Vert foncé'), ('#27AE60', 'Vert forêt foncé'), ('#2980B9', 'Bleu foncé'), ('#1ABC9C', 'Turquoise foncé'), ('linear-gradient(to right, #FF7F50, #FF1493)', 'Dégradé Rose-Orangé'), ('linear-gradient(to right, #2980B9, #8E44AD)', 'Dégradé Bleu-Violet'), ('linear-gradient(to right, #F39C12, #F1C40F)', 'Dégradé Jaune-Or'), ('#27AE60', 'Vert'), ('#2C3E50', 'Bleu marine'), ('#FFDAB9', 'Pêche'), ('#BDC3C7', 'Gris clair')], default='#000000', max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_settings', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='BoutiqueNavCusor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur_texte_cursor', models.CharField(choices=[('#000000', 'Noir'), ('#FFFFFF', 'Blanc'), ('#FF5733', 'Orange'), ('#33FF57', 'Vert'), ('#3357FF', 'Bleu'), ('#FFD700', 'Jaune'), ('#800080', 'Violet'), ('#FFC0CB', 'Rose'), ('#D3D3D3', 'Gris clair'), ('#3498DB', 'Bleu'), ('#FF5733', 'Orange vif'), ('#1ABC9C', 'Turquoise'), ('#E74C3C', 'Rouge'), ('#9B59B6', 'Violet'), ('#F39C12', 'Jaune'), ('#333333', 'Gris foncé'), ('#212121', 'Noir charbon'), ('#1A1A1A', 'Gris ardoise foncé'), ('#2C3E50', 'Bleu marine foncé'), ('#34495E', 'Gris bleu foncé'), ('#555555', 'Gris moyen foncé'), ('#7F8C8D', 'Gris ardoise'), ('#6A1B9A', 'Violet foncé'), ('#9B59B6', 'Violet prune'), ('#8E44AD', 'Violet foncé'), ('#E74C3C', 'Rouge foncé'), ('#C0392B', 'Rouge bordeaux'), ('#D35400', 'Orange brûlé'), ('#F39C12', 'Jaune foncé'), ('#16A085', 'Vert foncé'), ('#27AE60', 'Vert forêt foncé'), ('#2980B9', 'Bleu foncé'), ('#1ABC9C', 'Turquoise foncé'), ('linear-gradient(to right, #FF7F50, #FF1493)', 'Dégradé Rose-Orangé'), ('linear-gradient(to right, #2980B9, #8E44AD)', 'Dégradé Bleu-Violet'), ('linear-gradient(to right, #F39C12, #F1C40F)', 'Dégradé Jaune-Or'), ('#27AE60', 'Vert'), ('#2C3E50', 'Bleu marine'), ('#FFDAB9', 'Pêche'), ('#BDC3C7', 'Gris clair')], default='#000000', max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_cusor_nav', to='shop.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('publier', models.BooleanField(default=False)),
                ('html_contenu', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('premium', models.BooleanField(default=False)),
                ('statut_publication', models.CharField(choices=[('chargé', 'Chargé'), ('publié', 'Publié')], default='chargé', max_length=20)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('produits_vendus', models.CharField(blank=True, default='non', max_length=250)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='shop.utilisateur')),
            ],
            options={
                'db_table': 'shop_boutique',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InformationsSupplementairesTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_boutique', models.CharField(choices=[('petite', 'Petite Boutique'), ('croissance', 'Boutique en Croissance'), ('grande', 'Grande Boutique')], max_length=50)),
                ('produits_vendus', models.CharField(choices=[('Vêtements et accessoires', 'vetements'), ('Vêtements pour hommes', 'hommes'), ('Vêtements pour femmes', 'femmes'), ('Vêtements pour enfants', 'enfants'), ('Accessoires de mode', 'accessoires'), ('Alimentation et boissons', 'alimentaire'), ('Produits alimentaires de base', 'produits_basiques'), ('Fruits et légumes', 'fruits_legumes'), ('Boissons', 'boissons'), ('Produits laitiers', 'produits_laitiers'), ('Café et thé', 'cafe_the'), ('Électronique et appareils ménagers', 'electronique'), ('Téléphones mobiles et accessoires', 'smartphones'), ('Appareils électroménagers', 'appareils_electromenagers'), ('Ordinateurs et accessoires', 'ordinateurs'), ('Cosmétiques et soins personnels', 'cosmetiques'), ('Produits de beauté', 'beaute'), ('Produits d’hygiène', 'hygiene'), ('Parfums', 'parfums'), ("Matériel de construction et d'ameublement", 'construction'), ('Matériaux de construction', 'materiaux'), ('Meubles', 'meubles'), ('Décoration intérieure', 'decoration'), ('Produits de santé et médicaments', 'sante'), ('Médicaments en vente libre', 'medicaments'), ('Produits de bien-être', 'bien_etre'), ('Artisanat et objets traditionnels', 'artisanat'), ('Sculptures', 'sculptures'), ('Peintures', 'peintures'), ('Objets traditionnels', 'objets_traditionnels'), ('Automobiles et pièces détachées', 'automobile'), ("Véhicules neufs et d'occasion", 'vehicules'), ('Pièces détachées', 'pieces_detachees'), ('Produits agricoles', 'agricole'), ('Grains et céréales', 'grains'), ('Culture vivrière', 'vivrier'), ('Cultures industrielles', 'industriels'), ('Produits chimiques et agricoles', 'chimie_agricole'), ('Fertilisants', 'engrais'), ('Pesticides et herbicides', 'pesticides'), ('Semences', 'semences')], default='vetements', max_length=241)),
                ('source_decouverte', models.CharField(choices=[('reseaux_sociaux', 'Réseaux sociaux (Facebook, Instagram, Twitter, etc.)'), ('bouche_a_oreille', 'Bouche-à-oreille'), ('publicite', 'Publicité (en ligne, TV, etc.)'), ('recherche_google', 'Recherche Google'), ('blog_articles', 'Articles de blog ou forums'), ('email_marketing', 'Email marketing'), ('partenariats', 'Partenariats ou affiliations'), ('publications_mediatiques', 'Publications médiatiques (journaux, magazines, TV)'), ('autre', 'Autre')], max_length=100)),
                ('utilisateur_temporaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.utilisateurtemporaire')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(blank=True, max_length=20, null=True)),
                ('panier', models.BooleanField(default=False)),
                ('couleur', models.CharField(blank=True, choices=[('#FF5733', 'Rouge Orangée'), ('#FF6347', 'Tomate'), ('#FF4500', 'Rouge Orange'), ('#FF0000', 'Rouge'), ('#800000', 'Rouge Foncé'), ('#32CD32', 'Vert Lime'), ('#228B22', 'Vert Forêt'), ('#006400', 'Vert Foncé'), ('#008000', 'Vert'), ('#00FF00', 'Vert Clair'), ('#0000FF', 'Bleu'), ('#1E90FF', 'Bleu Dodger'), ('#4682B4', 'Bleu Acier'), ('#5F9EA0', 'Bleu Grisé'), ('#00008B', 'Bleu Marine'), ('#000080', 'Navy'), ('#8A2BE2', 'Violet'), ('#6A5ACD', 'Violet Cadet'), ('#7B68EE', 'Violet Clair'), ('#800080', 'Violet Foncé'), ('#FFD700', 'Or'), ('#FFFF00', 'Jaune'), ('#F0E68C', 'Jaune Pâle'), ('#DAA520', 'Or Marron'), ('#FFFACD', 'Jaune Clair'), ('#FF1493', 'Rose Chaud'), ('#FF69B4', 'Rose'), ('#C71585', 'Rose Fuchsia'), ('#D3D3D3', 'Gris Clair'), ('#A9A9A9', 'Gris'), ('#808080', 'Gris Moyen'), ('#696969', 'Gris Foncé'), ('#000000', 'Noir'), ('#FFFFFF', 'Blanc'), ('#D3D3D3', 'Gris Clair'), ('#F5F5F5', 'Gris Très Clair'), ('#C0C0C0', 'Argent'), ('#A52A2A', 'Marron'), ('#8B4513', 'Marron Foncé'), ('#D2691E', 'Chocolat'), ('#CD5C5C', 'Rouge Indien'), ('#F08080', 'Corail Clair'), ('#FA8072', 'Saumon'), ('#E9967A', 'Saumon Foncé'), ('#F4A460', 'Sable'), ('#D2B48C', 'Brun'), ('#FFF8DC', 'Blanc Crème')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variante/')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='shop.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='ventes/')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.BooleanField(default=False)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='shop.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='shop.utilisateur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_maps', models.CharField(max_length=1000)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('repere', models.CharField(blank=True, max_length=255, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='shop.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur',)},
            },
        ),
    ]
