# Generated by Django 5.1.4 on 2025-02-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='identifiant_unique',
            new_name='identifiant',
        ),
        migrations.RenameField(
            model_name='utilisateurtemporaire',
            old_name='identifiant_unique',
            new_name='identifiant',
        ),
    ]
