# Generated by Django 5.1.4 on 2025-03-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='identifiant_unique',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
