# Generated by Django 5.1.4 on 2025-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_identifiant_unique_utilisateur_identifiant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='identifiant',
            new_name='identifiant_unique',
        ),
        migrations.RenameField(
            model_name='utilisateurtemporaire',
            old_name='identifiant',
            new_name='identifiant_unique',
        ),
    ]
