# Generated by Django 5.1.4 on 2025-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_utilisateur_identifiant_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='identifiant_unique',
            field=models.CharField(default='warabaguinee224', max_length=100, unique=True),
        ),
    ]
