# Generated by Django 5.1.4 on 2025-02-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_variante_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='couleur',
            field=models.CharField(blank=True, choices=[('', ''), ('#FF5733', 'Rouge Orangée'), ('#FF6347', 'Tomate'), ('#FF4500', 'Rouge Orange'), ('#FF0000', 'Rouge'), ('#800000', 'Rouge Foncé'), ('#32CD32', 'Vert Lime'), ('#228B22', 'Vert Forêt'), ('#006400', 'Vert Foncé'), ('#008000', 'Vert'), ('#00FF00', 'Vert Clair'), ('#0000FF', 'Bleu'), ('#1E90FF', 'Bleu Dodger'), ('#4682B4', 'Bleu Acier'), ('#5F9EA0', 'Bleu Grisé'), ('#00008B', 'Bleu Marine'), ('#000080', 'Navy'), ('#8A2BE2', 'Violet'), ('#6A5ACD', 'Violet Cadet'), ('#7B68EE', 'Violet Clair'), ('#800080', 'Violet Foncé'), ('#FFD700', 'Or'), ('#FFFF00', 'Jaune'), ('#F0E68C', 'Jaune Pâle'), ('#DAA520', 'Or Marron'), ('#FFFACD', 'Jaune Clair'), ('#FF1493', 'Rose Chaud'), ('#FF69B4', 'Rose'), ('#C71585', 'Rose Fuchsia'), ('#D3D3D3', 'Gris Clair'), ('#A9A9A9', 'Gris'), ('#808080', 'Gris Moyen'), ('#696969', 'Gris Foncé'), ('#000000', 'Noir'), ('#FFFFFF', 'Blanc'), ('#D3D3D3', 'Gris Clair'), ('#F5F5F5', 'Gris Très Clair'), ('#C0C0C0', 'Argent'), ('#A52A2A', 'Marron'), ('#8B4513', 'Marron Foncé'), ('#D2691E', 'Chocolat'), ('#CD5C5C', 'Rouge Indien'), ('#F08080', 'Corail Clair'), ('#FA8072', 'Saumon'), ('#E9967A', 'Saumon Foncé'), ('#F4A460', 'Sable'), ('#D2B48C', 'Brun'), ('#FFF8DC', 'Blanc Crème')], default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='variante',
            name='quantite_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
