# Generated by Django 5.1.4 on 2025-03-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_utilisateur_identifiant_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
