# Generated by Django 5.1.4 on 2025-03-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutique',
            options={'managed': True, 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
    ]
