# Generated by Django 5.1.4 on 2025-03-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_boutique_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutique',
            options={'managed': True},
        ),
    ]
