# Generated by Django 5.1.4 on 2025-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_boutique_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='identifiant',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
