# Generated by Django 5.1.4 on 2025-03-30 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_boutique_identifiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutique',
            options={'managed': True, 'ordering': ['-date_publication'], 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
        migrations.AlterField(
            model_name='boutique',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description de la boutique'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='html_contenu',
            field=models.TextField(blank=True, verbose_name='Contenu HTML'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='identifiant',
            field=models.CharField(blank=True, help_text='Identifiant unique généré automatiquement', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la boutique'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Boutique premium'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='produits_vendus',
            field=models.CharField(blank=True, default='non', max_length=250, verbose_name='Produits vendus'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='publier',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='statut_publication',
            field=models.CharField(choices=[('chargé', 'Chargé'), ('publié', 'Publié')], default='chargé', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='shop.utilisateur', verbose_name='Propriétaire'),
        ),
    ]
