# Generated by Django 5.1.4 on 2025-03-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_boutique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='identifiant',
            field=models.UUIDField(null=True),
        ),
    ]
