# Generated by Django 5.1.4 on 2025-03-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_produit_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='identifiant',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
