# Generated by Django 5.1.4 on 2025-03-31 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_produit_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='ferme_jour_ferie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='heure_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='heure_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='jour_fermeture',
            field=models.CharField(blank=True, choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Samedi', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='jour_ouverture',
            field=models.CharField(blank=True, choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='localisation',
            name='ouvert_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='identifiant',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
