# Generated by Django 5.1.4 on 2025-04-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_localisation_ferme_jour_ferie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='ventes/')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_attente', to='shop.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_attente', to='shop.utilisateur')),
            ],
        ),
    ]
