# Generated by Django 5.1.4 on 2025-04-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_venteattente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteattente',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='vent/'),
        ),
    ]
