# Generated by Django 5.1.4 on 2025-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_boutique_logo_alter_commentaire_image_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la boutique'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil_images/'),
        ),
        migrations.AlterField(
            model_name='localimages',
            name='image',
            field=models.ImageField(upload_to='images_localisation/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produitimage',
            name='image',
            field=models.ImageField(upload_to='details/'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='supportclient',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='logo_boutique',
            field=models.ImageField(blank=True, null=True, upload_to='logos_boutiques/'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variante/'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='ventes/'),
        ),
        migrations.AlterField(
            model_name='venteattente',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='vent/'),
        ),
    ]
