# Generated by Django 5.1.4 on 2025-04-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_boutique_logo_alter_commentaire_image_profil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutiquesettings',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='detailcommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='detailcommande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='message',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='navbarsettings',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_boutique',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='BoutiqueNavCusor',
        ),
        migrations.DeleteModel(
            name='BoutiqueSettings',
        ),
        migrations.DeleteModel(
            name='DetailCommande',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='NavbarSettings',
        ),
    ]
