# Generated by Django 5.1.4 on 2025-04-13 10:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_boutiquesettings_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='image_profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profil_images'),
        ),
        migrations.AlterField(
            model_name='localimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images_localisation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='produits'),
        ),
        migrations.AlterField(
            model_name='produitimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='sliders'),
        ),
        migrations.AlterField(
            model_name='supportclient',
            name='profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profiles'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='logo_boutique',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logos_boutiques'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='variante'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='image_produit',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ventes'),
        ),
        migrations.AlterField(
            model_name='venteattente',
            name='image_produit',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vent'),
        ),
    ]
