# Generated by Django 5.2 on 2025-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_boutique_description_boutique_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='vue_par_boutiquier',
            field=models.BooleanField(default=False),
        ),
    ]
