# Generated by Django 5.2 on 2025-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_commande_vue_par_boutiquier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='vue_par_boutiquier',
            field=models.BooleanField(default=False),
        ),
    ]
