# Generated by Django 5.2 on 2025-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_vente_vue_par_boutiquier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='vue_par_boutiquier',
        ),
    ]
