# Generated by Django 5.2 on 2025-04-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_commande_vue_par_boutiquier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportclient',
            name='role',
            field=models.CharField(choices=[('verificateur_comptes', 'Vérificateur de Comptes'), ('controleur_produits', 'Contrôleur de Produits'), ('gestionnaire_comptes', 'Gestionnaire de Comptes')], max_length=50),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('est_premium', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='shop.utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.abonnement')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.supportclient')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.utilisateur')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
