# Generated by Django 5.2 on 2025-04-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_supportclient_role_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportclient',
            name='role',
            field=models.CharField(choices=[('verificateur_comptes', 'Vérificateur de Comptes'), ('controleur_produits', 'Contrôleur de Produits'), ('gestionnaire_comptes', 'Gestionnaire de Comptes'), ('gestionnaire_abonnements', 'Gestionnaire abonnement')], max_length=50),
        ),
    ]
