# Generated by Django 5.2 on 2025-04-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_utilisateur_date_creation_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_creation_compte',
        ),
    ]
