# Generated by Django 5.2 on 2025-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_utilisateur_date_creation_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='cree_par',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
