# Generated by Django 5.2 on 2025-05-09 22:46

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_abonnement_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_fin_essai',
            field=models.DateField(default=shop.models.default_date_fin_essai),
        ),
    ]
