# Generated by Django 5.2 on 2025-05-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_utilisateur_date_fin_essai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='date_mise_a_jour',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='est_premium',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.CharField(choices=[('1M', '1 Mois'), ('2M', '2 Mois'), ('3M', '3 Mois'), ('4M', '4 Mois'), ('5M', '5 Mois'), ('6M', '6 Mois'), ('7M', '7 Mois'), ('8M', '8 Mois'), ('9M', '9 Mois'), ('10M', '10 Mois'), ('11M', '11 Mois'), ('12M', '12 Mois')], default='1M', max_length=3),
        ),
    ]
